/*
* ============================================================================
*  Name     : CGameApp from GameApp.cpp
*  Part of  : Game
*  Created  : 31.1.2004 by Sami Kyöstilä
*  Implementation notes:
*
*     Initial content was generated by Series 60 AppWizard.
*  Version  :
*  Copyright: Sami Kyöstilä
* ============================================================================
*/

// INCLUDE FILES
#include    "GameApp.h"
#include    "GameDocument.h"

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CGameApp::AppDllUid()
// Returns application UID
// ---------------------------------------------------------
//
TUid CGameApp::AppDllUid() const
    {
    return KUidGame;
    }

   
// ---------------------------------------------------------
// CGameApp::CreateDocumentL()
// Creates CGameDocument object
// ---------------------------------------------------------
//
CApaDocument* CGameApp::CreateDocumentL()
    {
    return CGameDocument::NewL( *this );
    }

// ================= OTHER EXPORTED FUNCTIONS ==============
//
// ---------------------------------------------------------
// NewApplication() 
// Constructs CGameApp
// Returns: created application object
// ---------------------------------------------------------
//
EXPORT_C CApaApplication* NewApplication()
    {
    return new CGameApp;
    }

// ---------------------------------------------------------
// E32Dll(TDllReason) 
// Entry point function for EPOC Apps
// Returns: KErrNone: No error
// ---------------------------------------------------------
//
GLDEF_C TInt E32Dll( TDllReason )
    {
    return KErrNone;
    }

// End of File  

