/*
* ============================================================================
*  Name     : CGameDocument from GameDocument.h
*  Part of  : Game
*  Created  : 31.1.2004 by Sami Kyöstilä
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Version  :
*  Copyright: Sami Kyöstilä
* ============================================================================
*/

// INCLUDE FILES
#include "GameDocument.h"
#include "GameAppUi.h"

// ================= MEMBER FUNCTIONS =======================

// constructor
CGameDocument::CGameDocument(CEikApplication& aApp)
: CAknDocument(aApp)    
    {
    }

// destructor
CGameDocument::~CGameDocument()
    {
    }

// EPOC default constructor can leave.
void CGameDocument::ConstructL()
    {
    }

// Two-phased constructor.
CGameDocument* CGameDocument::NewL(
        CEikApplication& aApp)     // CGameApp reference
    {
    CGameDocument* self = new (ELeave) CGameDocument( aApp );
    CleanupStack::PushL( self );
    self->ConstructL();
    CleanupStack::Pop();

    return self;
    }
    
// ----------------------------------------------------
// CGameDocument::CreateAppUiL()
// constructs CGameAppUi
// ----------------------------------------------------
//
CEikAppUi* CGameDocument::CreateAppUiL()
    {
    return new (ELeave) CGameAppUi;
    }

// End of File  
